### ISSUE TITLE
Extract properties from page source

### ISSUE THREAD

**Issue by literarymachine** [skohub-io/skohub-extension#2]
Currently, we extract `title`, `url` and `meta.description` from a page. In https://github.com/hbz/skohub-extension/pull/1 we want to extend this to include e.g. https://ogp.me/ metadata. Which properties should we include, and how do they map to our [schema](https://raw.githubusercontent.com/literarymachine/oer-metadata-schemas/generic-OER/oer.json)?

**Comment by mandrasch** [comment]
I'm not sure what's going on exactly (😄), but I noticed there is no thumbnail_url in the schema?

**Comment by mandrasch** [comment]
Additionally: Here is my web page HTML crawler/analyzer https://github.com/programmieraffe/oerhoernchen20/blob/master/web/application/libraries/oerhoernchen/HtmlAnalyzer.php

**Comment by literarymachine** [comment]
> I'm not sure what's going on exactly (smile), but I noticed there is no thumbnail_url in the schema?

This is about creating a browser extension, feel free to give it a shot (see the README).

> I'm not sure what's going on exactly (smile), but I noticed there is no thumbnail_url in the schema?

We should probably add http://schema.org/image to our schema and map `og:image` and the like to it.

**Comment by acka47** [comment]
+1 please deploy
