### ISSUE TITLE
Open editor in sidebar

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-extension#3]
Instead of opening in a separate tab the editor should open in a side-bar similar to hypothes.is, see e.g. https://hyp.is/OxXmVgCaEeqEuAceNJRKSw/github.com/hbz/skohub-extension/issues/2

**Comment by literarymachine** [comment]
@acka47 to test this, just pull from master and reload the extension:

![image](https://user-images.githubusercontent.com/149825/68318902-c1e43980-00bd-11ea-89c1-d2234f7548a2.png)

**Comment by acka47** [comment]
Looks very good.
