### ISSUE TITLE
Problem with line breaks or parentheses in subject lookup

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-extension#6]
I just wanted to take a screenshot for the SWIB talk. Unfortunately the label "Information and Communication Technologies (ICTs)" is shown like this:

![Bildschirmfoto vom 2019-11-20 14-30-49](https://user-images.githubusercontent.com/160292/69243030-7001e000-0ba2-11ea-8ec3-7625f1765c62.png)

**Comment by literarymachine** [comment]
See https://test.skohub.io/editor/

![image](https://user-images.githubusercontent.com/149825/69347488-d7886000-0c74-11ea-9122-ad65e7460754.png)

**Comment by acka47** [comment]
Fixed. Closing.
